### ISSUE TITLE
TypeError: get_symbol() takes at least 10 arguments (12 given)

### ISSUE THREAD

**Issue by nigyiii** [MTCloudVision/mxnet-dssd#5]
你好，运行demo.py时出错，

Traceback (most recent call last):
  File "demo.py", line 152, in <module>
    ctx, len(class_names), args.nms_thresh, args.force_nms)
  File "demo.py", line 56, in get_detector
    force_nms=force_nms, nms_topk=nms_topk)
  File "/home/ogai/ngy/mxnet-dssd-master/symbol/symbol_factory.py", line 236, in get_symbol
    return symbol_builder.get_symbol(**config)
TypeError: get_symbol() takes at least 10 arguments (12 given)

请问您知道该怎么操作吗？

**Comment by xubo00** [comment]
请问您解决了吗?@nigyiii

**Comment by MTCloudVision** [comment]
@nigyiii 请问运行的是哪个demo？什么网络的呢？

**Comment by xubo00** [comment]
python demo.py基本上没有改变什么，vgg网络的， @MTCloudVision

**Comment by guagen** [comment]
我跑demo的时候也是这个问题，不知道是什么情况呢，是不是mxnet版本的问题

**Comment by guagen** [comment]
我的mxnet版本是1.2

**Comment by guagen** [comment]
但是卸载mxnet重新安装0.11版本的mxnet后还是出现这个问题。。。

**Comment by nigyiii** [comment]
你好，demo.py，是resnet50，设置都是默认 @MTCloudVision

**Comment by guagen** [comment]
你好，请问你解决了这个问题吗，我也在这个问题卡住了@nigyiii

**Comment by guagen** [comment]
我在想是不是因为vgg16_reduced的问题，我的vgg16_reduced是从别的地方下的，因为本程序中的vgg16下载地址失效了

**Comment by nigyiii** [comment]
@guagen 还没有。。。我后面有其他事情就没有继续看下去了

**Comment by guagen** [comment]
@nigyiii sad，你觉得有可能是啥问题

**Comment by guagen** [comment]
@nigyiii ，我看到一句话在输出中：(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.resnet50，会不会是这个原因

**Comment by guagen** [comment]
我好像查到是啥问题了，应该是某个函数传递参数出现了问题导致没跑通，过几天我忙完了把问题反馈一下吧
@nigyiii

**Comment by nigyiii** [comment]
好的，谢谢，辛苦！ @guagen

**Comment by xubo00** [comment]
查到是什么问题了吗? @guagen

**Comment by guagen** [comment]
@nigyiii @xubo0321 问题解决了，问题的根源在于这里的demo参数设置和ssd的demo参数设置是一样，所以根本无法初始化。我另开了一个issue，里面列出了我踩过的坑，根据那里改改，大体上可以把demo跑通了，有啥不会再咨询我吧。

**Comment by xubo00** [comment]
非常感谢大神，有问题再请教啦。 @guagen

**Comment by kireoxdz** [comment]
缺少topdown_layers, use_perdict_module， use_tdm=False, use_res_unit=False这几个参数，需要在symbol_factory.py的每个network下面添加这几个参数

**Comment by kireoxdz** [comment]
因为这个作者把get_symbol()这个函数的内容都改了，所以想用mobilenet，densenet系列，inceptionv3的都会报错

**Comment by bitwangdan** [comment]
@kireoxdz 你好，请问topdown_layers和use_predict_module赋什么值呀？

**Comment by bitwangdan** [comment]
@kireoxdz 我用的是densenet121哈
